
server:
  port: 8888

spring:

  application:
    name: config-application

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native, eureka-client
  security:
    user:
      password: password


#Profiles
#'data' profile only
---

spring.profiles: data

spring:
  datasource:
    url:
      jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecommerce
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #'eureka-client' profile only

---

spring.profiles: eureka-client

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    instance:
      hostname: localhost
      prefer-ip-address: true
