server:
  port: 8761
spring:
  application:
    registry-application

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    instance:
      hostname: localhost
      preferIpAddress: true