

spring:
  profiles:
    active: "eureka-client"
  application:
    name: gateway-application

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    instance:
      hostname: localhost
      prefer-ip-address: true