spring:
  profiles:
    active: "eureka-client"
  application:
    name: product-application

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

feign:
  client:
    config:
      httpBinClient:
        read-timeout: 2000
        connect-timeout: 1000
  circuitbreaker:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 1
      slidingWindowType: TIME_BASED
      waitDurationInOpenState: 5s
      eventConsumerBufferSize: 10
      minimumNumberOfCalls: 4
      failureRateThreshold: 50
